// <auto-generated />
namespace Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changemanagerclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changemanagerclass));
        
        string IMigrationMetadata.Id
        {
            get { return "201711262011252_change manager class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
